<?xml version="1.0"?>

<robot name="arm5e_A" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:property name="pi" value="3.1415926535897931"/>
  <xacro:property name="pi" value="3.141592654" />
  <xacro:property name="robot_parts_path" value="robot/ARM5E/ARM5E" />  
  <xacro:property name="ext" value="osg" />
  
  <xacro:property name="theta1" value="0.139277274" />
  <xacro:property name="theta2" value="1.972222055" />
  
  <xacro:property name="cosTheta1" value="0.990316589" />  
  <xacro:property name="sinTheta1" value="0.138827424" />
  
  <xacro:property name="cos180minusTheta2" value="0.390731128" />  
  <xacro:property name="sin180minusTheta2" value="0.920504853" />
  
  <!-- Arm properties -->
  <xacro:property name="arm_mass" value="1"/>
  <xacro:property name="arm_radius" value="0.10"/>
  <xacro:property name="jaw_mass" value="0.1"/>
  <xacro:property name="jaw_radius" value="0.05"/>  
  <xacro:property name="eps" value="0.00000001"/>
  
  
  <!-- Cylinder inertial matrix -->
  <xacro:macro name="cyl_inertial" params="mass radius length">
    <inertial>
      <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass*(radius*radius/4+length*length/12)}"
	  ixy="0.0"
	  ixz="0.0"
	  iyy="${mass*(radius*radius/4+length*length/12)}"
	  iyz="0.0"
	  izz="${mass*radius*radius/2}"/>
    </inertial>
  </xacro:macro>
  
  <!-- Sphere inertial matrix -->
  <xacro:macro name="sph_inertial" params="mass radius">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${2/5*mass*radius*radius}"
	  ixy="0.0"
	  ixz="0.0"
	  iyy="${2/5*mass*radius*radius}"
	  iyz="0.0"
	  izz="${2/5*mass*radius*radius}"/>
    </inertial>
  </xacro:macro>
  
  
  <!-- Begin arm joints and links -->
  

  <link name="part0">
    <visual>
      <origin rpy="${pi} 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file://$(env HOME)/.uwsim/data/robot/ARM5E/ARM5E_part0.dae"/>
      </geometry>
    </visual>
    <xacro:sph_inertial mass="${arm_mass}" radius="${arm_radius}" />
    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

  <joint name="baselink_to_part0" type="fixed">
    <parent link="base_link"/>
    <child link="part0"/>
    <origin rpy="0 0 ${pi}" xyz="0 0 0.95"/>
  </joint>

 <link name="part1">
    <visual>
      <origin rpy="${pi} 0 0" xyz="0.0 0 -0.13"/>
      <geometry>
        <mesh filename="file://$(env HOME)/.uwsim/data/robot/ARM5E/ARM5E_part1.dae"/>
      </geometry>
    </visual>
     <xacro:sph_inertial mass="${arm_mass}" radius="${arm_radius}" />
    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

  <joint name="Slew" type="revolute">
    <parent link="part0"/>
    <child link="part1"/>
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="0 0 0.13"/>
    <dynamics damping="0.8"/>
    <limit lower="${-pi/2}" upper="0.5488" velocity="1" effort="500"/>
  </joint>

 <link name="part2">
    <visual>
      <origin rpy="${pi/2} 0 -${0.22654-theta1}" xyz="0 0 0"/> 
      <geometry>
        <mesh filename="file://$(env HOME)/.uwsim/data/robot/ARM5E/ARM5E_part2.dae"/>
      </geometry>
    </visual>
     <xacro:sph_inertial mass="${arm_mass}" radius="${arm_radius}" />
    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

  <joint name="Shoulder" type="revolute">
    <parent link="part1"/>
    <child link="part2"/>
    <axis xyz="0 0 1"/>
    <origin rpy="${pi/2} 0 0" xyz="0.08052 0 0"/>
    <dynamics damping="0.8"/>
    <limit effort="500.0" lower="0" upper="1.58665" velocity="1.0"/>  
  </joint>

 <link name="part3">
    <visual>
      <origin rpy="${pi/2} 0 0.4014" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file://$(env HOME)/.uwsim/data/robot/ARM5E/ARM5E_part3.dae"/>
      </geometry>
    </visual>
    <xacro:sph_inertial mass="${arm_mass}" radius="${arm_radius}" />
    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

  <joint name="Elbow" type="revolute">
    <parent link="part2"/>
    <child link="part3"/>
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 ${theta1}" xyz="${cosTheta1*0.44278} ${sinTheta1*0.44278} 0"/> 
    <dynamics damping="0.8"/>
    <limit effort="500.0" lower="0" upper="2.15294" velocity="1.0"/>
    </joint>

  <link name="part4_base">
    <visual>
      <origin xyz="0 0 -0.028" rpy="0 -${pi/2} 0" />
      <geometry>
        <mesh filename="file://$(env HOME)/.uwsim/data/robot/ARM5E/ARM5E_part4_base.dae"/>
      </geometry>
    </visual>
    <xacro:sph_inertial mass="${jaw_mass}" radius="${jaw_radius}" />
    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

    
    <joint name="JawRotate" type="continuous">
    <parent link="part3"/>
    <child link="part4_base"/>
    <axis xyz="0 0 1"/>
    <origin rpy="${pi/2} 0 ${theta2}" xyz="${0.083/cos180minusTheta2+sin180minusTheta2*0.1485} ${cos180minusTheta2*0.1485} 0"/>
    </joint>
    
      <link name="end_effector"> <!-- From the kinematic base of the robot -->
  </link>
  
  <joint name="part4_base_to_end_effector" type="fixed">
    <parent link="part4_base"/>
    <child link="end_effector"/>
    <origin rpy="0 0 0" xyz="0 0 0.1485"/>
  </joint>
  
  <link name="peg"> 
  </link>
  
  <joint name="ee_to_peg" type="fixed">
    <parent link="end_effector"/>
    <child link="peg"/>
    <origin rpy="0 0 -1.5707991565684896" xyz="-0.000005641198616 -1.9999781062135944 0.006895626409301414"/>
  </joint>

  
    
        
  <link name="part4_jaw1">
    <visual>
      <origin rpy="0 -${pi/2} 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file://$(env HOME)/.uwsim/data/robot/ARM5E/ARM5E_part4_jaw1.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 -${pi/2} 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file://$(env HOME)/.uwsim/data/robot/ARM5E/ARM5E_part4_jaw1.dae"/>
      </geometry>
    </collision>
    <xacro:sph_inertial mass="${jaw_mass}" radius="${jaw_radius}" />
    <buoyancy><compensation>1.0</compensation></buoyancy>
  </link>

  <joint name="JawOpening" type="revolute">
    <parent link="part4_base"/>
    <child link="part4_jaw1"/>
    <axis xyz="0 -1 0"/>
    <origin rpy="0 0 0" xyz="-0.04 0 0.045"/>
    <dynamics damping="0.8"/>
    <limit effort="100.0" lower="-0.05816" upper="1.337696" velocity="1.0"/> 
    </joint>

<link name="part4_jaw2">
    <visual>
      <origin rpy="0 -${pi/2} 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file://$(env HOME)/.uwsim/data/robot/ARM5E/ARM5E_part4_jaw2.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 -${pi/2} 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file://$(env HOME)/.uwsim/data/robot/ARM5E/ARM5E_part4_jaw2.dae"/>
      </geometry>
    </collision>
    <xacro:sph_inertial mass="${jaw_mass}" radius="${jaw_radius}" />
    <buoyancy><compensation>1.0</compensation></buoyancy>
    </link>

  <joint name="JawOpening2" type="revolute">
    <parent link="part4_base"/>
    <child link="part4_jaw2"/>
    <axis xyz="0 1 0"/>
    <origin rpy="0 0 0" xyz="0.04 0 0.0450"/>
    <dynamics damping="0.8"/>
    <limit lower="-0.05816" upper="1.337696" velocity="1.0" effort="100"/>
    </joint>

</robot>

